apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-artifactory
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-arti-headless
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-jrc
        image: "{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        ports:
        - containerPort: {{ .Values.uiPort }}
          name: ui
