apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-artifactory
  labels:
    app: {{ .Release.Name }} 
spec:
  type: NodePort
  ports:
  - port: 8082
    nodePort: 32082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }} 
